"use strict";(self.webpackChunkmy_project=self.webpackChunkmy_project||[]).push([[6394],{36833:(K,p,t)=>{t.d(p,{pl:()=>C,aY:()=>$,q5:()=>P});var e=t(53547),r=t(5504),f=t(25804),A=t(18172);const T={data:[],isLoading:!0},l=(a,E)=>(0,A.default)(a,n=>{switch(E.type){case"GET_DATA_SUCCEEDED":{n.data=E.data,n.isLoading=!1;break}case"GET_DATA_ERROR":{n.isLoading=!1;break}default:return n}}),C=({ssoEnabled:a})=>{const[E,n]=(0,e.useReducer)(l,T),L=(0,r.useNotification)(),{get:O}=(0,r.useFetchClient)();return(0,e.useEffect)(()=>{(async()=>{try{if(!a){n({type:"GET_DATA_SUCCEEDED",data:[]});return}const{data:_}=await O((0,f.IF)("providers"));n({type:"GET_DATA_SUCCEEDED",data:_})}catch(_){console.error(_),n({type:"GET_DATA_ERROR"}),L({type:"warning",message:{id:"notification.error"}})}})()},[O,a,L]),E};var h=t(14293),g=t.n(h),v=t(86896),I=t(16550),c=t(75336),d=t(7694),m=t(36364);function s(){const a=(0,d.v9)(m._),{get:E}=(0,r.useFetchClient)(),{isLoading:n,allowedActions:{canRead:L,canCreate:O,canUpdate:y,canDelete:_}}=(0,r.useRBAC)(a.settings.users),U=L&&O&&y&&_,{data:u,isError:S,isLoading:B}=(0,c.useQuery)(["ee","license-limit-info"],async()=>{const{data:{data:W}}=await E("/admin/license-limit-information");return W},{enabled:!n&&U}),M=u??{},Z=e.useCallback(W=>(M?.features??[]).find(x=>x.name===W)?.options??{},[M?.features]);return{license:M,getFeature:Z,isError:S,isLoading:B}}const P=s,D="strapi-notification-seat-limit",i="https://cloud.strapi.io/profile/billing",N="https://strapi.io/billing/request-seats",$=()=>{const{formatMessage:a}=(0,v.Z)();let{license:E,isError:n,isLoading:L}=P();const O=(0,r.useNotification)(),{pathname:y}=(0,I.TH)(),{enforcementUserCount:_,permittedSeats:U,licenseLimitStatus:u,isHostedOnStrapiCloud:S}=E;(0,e.useEffect)(()=>{if(n||L)return;const B=!g()(U)&&!window.sessionStorage.getItem(`${D}-${y}`)&&(u==="AT_LIMIT"||u==="OVER_LIMIT");let M;u==="OVER_LIMIT"?M="warning":u==="AT_LIMIT"&&(M="softWarning"),B&&O({type:M,message:a({id:"notification.ee.warning.over-.message",defaultMessage:"Add seats to {licenseLimitStatus, select, OVER_LIMIT {invite} other {re-enable}} Users. If you already did it but it's not reflected in Strapi yet, make sure to restart your app."},{licenseLimitStatus:u}),title:a({id:"notification.ee.warning.at-seat-limit.title",defaultMessage:"{licenseLimitStatus, select, OVER_LIMIT {Over} other {At}} seat limit ({enforcementUserCount}/{permittedSeats})"},{licenseLimitStatus:u,enforcementUserCount:_,permittedSeats:U}),link:{url:S?i:N,label:a({id:"notification.ee.warning.seat-limit.link",defaultMessage:"{isHostedOnStrapiCloud, select, true {ADD SEATS} other {CONTACT SALES}}"},{isHostedOnStrapiCloud:S})},blockTransition:!0,onClose(){window.sessionStorage.setItem(`${D}-${y}`,!0)}})},[O,E,y,a,L,U,u,_,S,n])}},76394:(K,p,t)=>{t.r(p),t.d(p,{LoginEE:()=>d});var e=t(53547),r=t(81984),f=t(50781),A=t(75878),T=t(78549),R=t(45697),l=t.n(R),o=t(86896),C=t(88972),h=t(50745),g=t(31640),v=t(36833),I=t(80090);const c=(0,C.default)(r.i)`
  flex: 1;
`,d=m=>{const s=window.strapi.features.isEnabled(window.strapi.features.SSO),{isLoading:P,data:D}=(0,v.pl)({ssoEnabled:s}),{formatMessage:i}=(0,o.Z)();return!s||!P&&D.length===0?e.createElement(h.ZP,null,e.createElement(g.Z,{...m})):e.createElement(h.ZP,null,e.createElement(g.Z,{...m},e.createElement(f.x,{paddingTop:7},e.createElement(A.k,{direction:"column",alignItems:"stretch",gap:7},e.createElement(A.k,null,e.createElement(c,null),e.createElement(f.x,{paddingLeft:3,paddingRight:3},e.createElement(T.Z,{variant:"sigma",textColor:"neutral600"},i({id:"Auth.login.sso.divider"}))),e.createElement(c,null)),e.createElement(I.Z,{providers:D,displayAllProviders:!1})))))};d.defaultProps={onSubmit:m=>m.preventDefault(),requestError:null},d.propTypes={formErrors:l().object.isRequired,modifiedData:l().object.isRequired,onChange:l().func.isRequired,onSubmit:l().func,requestError:l().object}},80090:(K,p,t)=>{t.d(p,{Z:()=>m});var e=t(53547),r=t(75878),f=t(74273),A=t(78549),T=t(9370),R=t(61585),l=t(45697),o=t.n(l),C=t(86896),h=t(73727),g=t(88972);const v=g.default.a`
  width: ${136/16}rem;
  display: flex;
  justify-content: center;
  align-items: center;
  height: ${48/16}rem;
  border: 1px solid ${({theme:s})=>s.colors.neutral150};
  border-radius: ${({theme:s})=>s.borderRadius};
  text-decoration: inherit;
  &:link {
    text-decoration: none;
  }
  color: ${({theme:s})=>s.colors.neutral600};
`,I=(0,g.default)(r.k)`
  & a:not(:first-child):not(:last-child) {
    margin: 0 ${({theme:s})=>s.spaces[2]};
  }
  & a:first-child {
    margin-right: ${({theme:s})=>s.spaces[2]};
  }
  & a:last-child {
    margin-left: ${({theme:s})=>s.spaces[2]};
  }
`,c=({provider:s})=>e.createElement(f.u,{label:s.displayName},e.createElement(v,{href:`${window.strapi.backendURL}/admin/connect/${s.uid}`},s.icon?e.createElement("img",{src:s.icon,"aria-hidden":!0,alt:"",height:"32px"}):e.createElement(A.Z,null,s.displayName)));c.propTypes={provider:o().shape({icon:o().string,displayName:o().string.isRequired,uid:o().string.isRequired}).isRequired};const d=({providers:s,displayAllProviders:P})=>{const{formatMessage:D}=(0,C.Z)();return P?e.createElement(T.r,{gap:4},s.map(i=>e.createElement(R.P,{key:i.uid,col:4},e.createElement(c,{provider:i})))):s.length>2&&!P?e.createElement(T.r,{gap:4},s.slice(0,2).map(i=>e.createElement(R.P,{key:i.uid,col:4},e.createElement(c,{provider:i}))),e.createElement(R.P,{col:4},e.createElement(f.u,{label:D({id:"global.see-more"})},e.createElement(v,{as:h.Link,to:"/auth/providers"},e.createElement("span",{"aria-hidden":!0},"\u2022\u2022\u2022"))))):e.createElement(I,{justifyContent:"center"},s.map(i=>e.createElement(c,{key:i.uid,provider:i})))};d.defaultProps={displayAllProviders:!0},d.propTypes={providers:o().arrayOf(o().object).isRequired,displayAllProviders:o().bool};const m=d}}]);
